#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WeatherApp.Resource", IsApplication=true)]

namespace WeatherApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AMShowersWind = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bluesun = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ClearSky = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Cloudy = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Cold = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int delete = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Drizzle = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int edit = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Fog = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Hail = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Haze = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Hot = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Hurricane = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Icon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int LightRain = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int LightRainShower = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int logo = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int MostlyCloudy = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int MostlyCloudyWind = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int MostlyCloudyWindy = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int MostlySunny = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int MostlySunnyWind = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int NAImage = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int PartlyCloudy = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int PartlyCloudyWind = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int PMLightRainWind = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int PMShowers = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int Rain = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int RainWind = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ShowersLate = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ShowersVicinity = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int Sleet = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int Snow = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int sunicon = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int Sunny = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ThunderShowers = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int Thunderstorms = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int Tornado = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int weather = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int weathericon = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int Windy = 2130837544;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int Text1 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Text2 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int Text3 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int btnImage = 2131034115;
			
			// aapt resource value: 0x7f050012
			public const int imgWeatherIcon = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int lblConditionText = 2131034131;
			
			// aapt resource value: 0x7f050004
			public const int lblCurrentLocation = 2131034116;
			
			// aapt resource value: 0x7f050016
			public const int lblForeCastHeadingTxt = 2131034134;
			
			// aapt resource value: 0x7f05000c
			public const int lblHumidity = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int lblLine1WC = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int lblLine2WC = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int lblLine3WC = 2131034127;
			
			// aapt resource value: 0x7f050018
			public const int lblPoweredBy = 2131034136;
			
			// aapt resource value: 0x7f050014
			public const int lblSunrise = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int lblSunset = 2131034133;
			
			// aapt resource value: 0x7f05000b
			public const int lblTempWC = 2131034123;
			
			// aapt resource value: 0x7f050008
			public const int lblTemparature = 2131034120;
			
			// aapt resource value: 0x7f050010
			public const int lblVisibility = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int lblWindSpeed = 2131034126;
			
			// aapt resource value: 0x7f050011
			public const int llImgWraper = 2131034129;
			
			// aapt resource value: 0x7f050007
			public const int llWeatherDataTxt = 2131034119;
			
			// aapt resource value: 0x7f050017
			public const int lstForecast = 2131034135;
			
			// aapt resource value: 0x7f050006
			public const int rlTopMainContainer = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int txtSearch = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int version = 2131034121;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CustomRow = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
